# Railway.app configuration file
[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 2"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 60
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  PYTHONPATH = "/app"
  FLASK_ENV = "production"
  ENVIRONMENT = "production"